# theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/modernist@v0.2.0
# remote_theme: pages-themes/merlot@v0.2.0
title: jmoreno - apunts
description: Materials docents per a cicles formatius d'Informàtica
show_downloads: false
